# -*- coding: utf-8 -*-
"""Resolucao_Biquadradas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HuMWHoQjm1qDxAg0R5iyPtH3QvUky4RO
"""

import math
import numpy as np
import matplotlib.pyplot as plt

def resolver_biquadrada():
    print("--- Solucionador de Equações Biquadradas (ax^4 + bx^2 + c = 0) ---")

    # ------------------------- ALOCAÇÃO DE DADOS ---------------------------
    try:
        a = float(input("Digite o valor de a: "))
        b = float(input("Digite o valor de b: "))
        c = float(input("Digite o valor de c: "))
    except ValueError:
        print("[ERRO]: Digite apenas números válidos.")
        return

    # ------------------------ VERIFICAÇÃO DOS DADOS ------------------------
    if a == 0:
        print("[ERRO]: O valor de a não pode ser zero em uma equação biquadrada.")
        return

    print(f"\nProcedimento: Substituindo u = x^2, temos a equação: {a}u^2 + {b}u + {c} = 0")

    delta = b**2 - 4*a*c
    print(f"Resultado Parcial: Delta (u) = {delta:.4f}")

    if delta < 0:
        print("Interrupção: O discriminante é negativo. As raízes em u são complexas.")
        return

    # --------------------------- CÁLCULO DAS RAÍZES ------------------------
    sqrt_delta = math.sqrt(delta)
    u1 = (-b + sqrt_delta) / (2*a)
    u2 = (-b - sqrt_delta) / (2*a)
    print(f"Resultado Parcial: Raízes para u: u1 = {u1:.4f}, u2 = {u2:.4f}")

    raizes_reais = []

    # Verificação se u permite raiz real (u >= 0)
    for u in (u1, u2):
        if u > 0:
            raiz_x = math.sqrt(u)
            raizes_reais.extend([raiz_x, -raiz_x])
        elif u == 0:
            raizes_reais.append(0.0)

    # ----------------------- PROCESSAMENTO FINAL E SAÍDA -------------------
    # Eliminar duplicatas e ordenar
    raizes_reais = sorted(list(set(raizes_reais)))

    # Interrupção se não houver raízes reais
    if not raizes_reais:
        print("Interrupção: Não existem raízes no domínio dos Reais (u < 0).")
        return

    # Exibição dos resultados finais
    print(f"\nDomínio da solução: Real (x ∈ ℝ)")
    print(f"Número de raízes encontradas: {len(raizes_reais)}")
    print(f"Raízes: {raizes_reais}")

    # ----------------------- GERAÇÃO DE GRÁFICO -----------------------------
    # Gráfico isolado no escopo operacional, garantindo acesso seguro a "a, b, c" e "raizes_reais"

    margem = max(abs(max(raizes_reais, default=2)), 2) + 1
    x_plot = np.linspace(-margem, margem, 500)
    y_plot = a*x_plot**4 + b*x_plot**2 + c

    plt.figure(figsize=(10, 6))
    plt.plot(x_plot, y_plot, label=f'f(x) = {a}x⁴ + {b}x² + {c}', color='blue', lw=2)

    # Eixos de referência
    plt.axhline(0, color='black', linestyle='--', linewidth=1)
    plt.axvline(0, color='black', linestyle='--', linewidth=1)

    # Plot das raízes no gráfico (Indentação corrigida)
    plt.scatter(raizes_reais, [0]*len(raizes_reais), color='red', zorder=5, label='Raízes Reais')

    # Configurações visuais do plot
    plt.title("Gráfico da Função Biquadrada")
    plt.xlabel("x")
    plt.ylabel("f(x)")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()

# Ponto de entrada protegido e blindado
if __name__ == "__main__":
    resolver_biquadrada()